require 'dotenv/load'

require 'capistrano/setup'
require 'capistrano/deploy'
require 'capistrano/scm/git'
install_plugin Capistrano::SCM::Git

require 'capistrano/rails'
require 'capistrano/rails/console'
require 'capistrano/rbenv'
require 'capistrano3/unicorn'
require 'capistrano/yarn'

Dir.glob('lib/capistrano/tasks/*.rake').each { |r| import r }