source 'https://rubygems.org'


gem 'rails', '4.2.3'

gem 'coffee-rails', '~> 4.1.0'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'sass-rails', '~> 5.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'uglifier', '>= 1.3.0'

group :development, :test do
  gem 'fuubar'
  gem 'guard-rspec'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'quiet_assets'
  gem 'rspec-rails'
  gem 'spring'
  gem 'terminal-notifier-guard'
  gem 'web-console', '~> 2.0'
end

