source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.1'

gem 'activerecord-import'
gem 'bootsnap', '>= 1.1.0', require: false
gem 'chartkick'
gem 'html2slim', '~> 0.2.0'
gem 'puma', '~> 3.11'
gem 'rails', '5.2.3'
gem 'rails-i18n', '~> 5.1'
gem 'sassc-rails'
gem 'slim-rails'
gem 'turbolinks', '~> 5'
gem 'uglifier', '>= 1.3.0'

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'mysql2', '>= 0.4.4', '< 0.6.0'
end

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'pry-rails'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :production do
  gem 'pg', '~> 0.18.0'
end

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
