# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 05:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.IntegerField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('daylight', models.FloatField()),
                ('energy_production', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('number_of_people', models.IntegerField()),
                ('has_child', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='energy',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.House'),
        ),
    ]
